### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by dr-nyt** [mordechaim/Swing-Slide-Menu#1]
Hey!
I'm really interested in your project. I want to have a phone like the hamburger menu in my desktop app and would really appreciate it if you could let me know how to use this project.

**Comment by mordechaim** [comment]
Don't bet on this, it's a dead project I've been working on when I was still a novice programmer barely in my mid-teens. It violates many best practices, and programming design paradigms.

I myself don't remember how to use it; in any event, who still uses Swing? For JavaFX there are many popular projects doing just this — JFeoniX for one.

**Comment by dr-nyt** [comment]
I just started out programming as well :D I didn't know that Swing is discreet now, no wonder it's so clunky to use, even with NetBeans GUI designer. I'll try JFeonix, although I'll have to see how to set it up first ;3

**Comment by dr-nyt** [comment]
Hey sorry to bother you, but I looked into JFeonix and apparently to use it with Netbeans I'll have to create a new project with JavaFX, but then I won't have the Gradle. I'd really appreciate it if you could guide me in the correct direction :D

**Comment by mordechaim** [comment]
I've never used Netbeans but in Eclipse you can create a JavaFX project and later select 'add Gradle nature'. I'm sure Netbeans has a similar concept.
